enemy_turn = false
win = false 
lose = false
is_going = true
has_gone = 0 
enemy = [enemya,enemyb,enemyc]
i= -1
which_person = 0
random_add = 0
def_attk =0
big_attk = 0
miss_attk = 0
strob_hit = 0
strob_count = 0
alarm[0] = 1
alarm[2] = 1